### ISSUE TITLE
Is it intended to be working with php-fpm?

### ISSUE THREAD

**Issue by white-gecko** [duncan3dc/fork-helper#1]
I've heard/read different things about forking and php-fpm. Some said its only on working with the php apache module, some say its not working with php-fpm as well ([stackoverflow](https://stackoverflow.com/questions/35026153/call-to-undefined-function-pcntl-fork-php-fpm-nginx)), but it seams to be working with php-cli.
It would be cool, if you could point out the compatibility resp. the requirements for you helper to help ;-)

Thank you

**Comment by duncan3dc** [comment]
I've only ever used this package with php-cli. I think that's all the underlying functions/extension are compatible with.
So no support for fpm I'm afraid, sorry
