### ISSUE TITLE
When I call my API the fork slows down really badly.

### ISSUE THREAD

**Issue by msaus** [duncan3dc/fork-helper#12]
Hello there,

When I call my API, the fork slows down really badly.

Is there anything I can do for this issue?

Best regards,

**Comment by duncan3dc** [comment]
Buy more/faster CPUs :laughing: 

If this is related to #11 then I'd suggest spawning less jobs, it seems 100 is too many for the machine you are running on.

I normally only fork 5-10 times

**Comment by msaus** [comment]
I see.
Thank you very much for your help.
