### ISSUE TITLE
returning data using the same shared memory

### ISSUE THREAD

**Issue by Byter09** [duncan3dc/fork-helper#13]
Lets say there is a method called `getResult()`, returning all results of all `call()` methods or of individual processes - much like `wait()` can wait for all or a single one.

Would it be possible to return a simple string? This alone would be enough to send through _serialized_ data. Maybe even change the `call()` method to use serialized data?

Thanks in advance.

**Comment by duncan3dc** [comment]
Hi Kevin, I'm so sorry for the delay here, I somehow missed this issue when you first raised it.

Are you still interested in this feature? It sounds like something I could look into for you

**Comment by Byter09** [comment]
Hey.

As much as I still like such a feature, I moved on to [Rust](https://www.rust-lang.org/) and totally forgot this issue too. I have not used PHP or this library for nearly a year now haha.

I guess this can be closed then? :yum:

**Comment by duncan3dc** [comment]
I guess so! Sorry again, happy coding
