### ISSUE TITLE
Tagging new Version

### ISSUE THREAD

**Issue by mattagohni** [duncan3dc/fork-helper#14]
Hello,

is it possible that you tag a new version. In the master branch is a fix that I would like to use. (#10 ) But there was no release since this PR was merged. It would help me a lot, since I only can use tagged versions in my environment and no dev-master.

Best Regards
Matthias

**Comment by duncan3dc** [comment]
Hi Matthias,

I'll get a release tagged this week for you

**Comment by mattagohni** [comment]
Perfect. Thank you for your quick response!

**Comment by duncan3dc** [comment]
I've tagged [2.2.1](https://github.com/duncan3dc/fork-helper/releases/tag/2.2.1) for you now
