### ISSUE TITLE
Help me to take a tag version 1.1.6

### ISSUE THREAD

**Issue by ihalton** [duncan3dc/fork-helper#4]
Dear Coder,
I like the project very well. It is very simple and useful, so I used it in my project with composer some days ago, but my php version is 5.6, and now I can not use your newest version. Can you help me make a tag version 1.1.6 at the commit:6eebe41566f7df96e9e411f0a509d7559360adf7, because I had used your function : getPIDs() ? if you do it ,I can use it now, because my project is only support php version 5.6, it can not work in your newest version. Thank you !

**Comment by duncan3dc** [comment]
Hi @ihalton, that shouldn't be a problem, I'll take a look this weekend.
As it was never tagged, were you using `dev-master`?

**Comment by ihalton** [comment]
yes, because the function getPIDS have been in only dev-master some months ago. so if you help me make a tag version 1.1.6, so I can composer update with the tag version in my project. Thank you very much!

**Comment by duncan3dc** [comment]
I understand, it's unfortunate you didn't ask for this tag then instead of using `dev-master` as it looks like 6eebe41566f7df96e9e411f0a509d7559360adf7 already requires php7 in `composer.json` now.

I'll have to create a branch for `1.1.*` support and see what I can backport

**Comment by ihalton** [comment]
I only need you to help me make a tag version:1.1.6, which can support php5.6 and have function :getPIDs , so that I can composer the version:1.1.6 in my project.

**Comment by ihalton** [comment]
can you help me to do it as soon as possible ? Thank you for your kindly .

**Comment by sergeyklay** [comment]
@duncan3dc ping

**Comment by duncan3dc** [comment]
Can you test out `duncan3dc/fork-helper:1.1.x-dev` to see if that gives you what you need? If so I'll tag that as `1.1.6`

**Comment by duncan3dc** [comment]
@sergeyklay @ihalton Have either of you tested that the `1.1.x` branch provides what you need?

**Comment by sergeyklay** [comment]
I'll try tomorrow

**Comment by ihalton** [comment]
@duncan3dc Thank you very much! please tag it as version 1.1.6 for the branch 1.1

**Comment by duncan3dc** [comment]
This is available now (https://github.com/duncan3dc/fork-helper/releases/tag/1.1.6)
