### ISSUE TITLE
Warning: shmop_open(): unable to attach or create shared memory segment 'No space left on device'

### ISSUE THREAD

**Issue by martijnhartlief** [duncan3dc/fork-helper#7]
After using this for a while I get this:
`Warning: shmop_open(): unable to attach or create shared memory segment 'No space left on device'`

When you call:
`$ ipcs -m`
You'll see a huge list of memory sections claimed by the forker.

I have a feeling that somehow the memory allocation is not cleared when something unexpected happens.

On MacOS this happens almost right away. And on Linux it takes many cycles before this occurs.

**Comment by duncan3dc** [comment]
I don't think the shared memory is ever cleared. I had a look at doing so automatically on `__destruct()` but this isn't possible as the `SharedMemory` object doesn't know when it's safe to destroy the memory.

I'll take a look at some kind of manual option to clean up the shared memory

**Comment by duncan3dc** [comment]
Hi @martijnhartlief, thanks for reporting this. It's fixed in version `2.2.0` now, as long as you call `wait()` the shared memory will be deleted

**Comment by Moskito89** [comment]
This problem still exists in v2.3.0...

**Comment by duncan3dc** [comment]
Hi @Moskito89, please could you provide a script to reproduce your problem, it might also be best to raise a new issue for this problem, thanks

**Comment by Moskito89** [comment]
> Hi @Moskito89, please could you provide a script to reproduce your problem, it might also be best to raise a new issue for this problem, thanks

It's [here](https://github.com/duncan3dc/fork-helper/issues/16) :-)
